### PR TITLE
Add Style to Users

### PR DESCRIPTION
**Pull request by dborski**
## Description
Completes Issue #36
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Notes
- Adding `stylePreferences` column to users table so that we can save the user's style preference
- Add knex.js library to project

### CODE REVIEW

**Review by attom2 — COMMENTED** [review]
Aren't we supposed to be rebasing? How do we go about that?

**Comment by dborski** [comment]
Good point. Let's chat about it this morning.

**Comment by muydanny** [comment]
Great catch, Andy. Other than that Im glad wee were able to get a good start on this.

**Comment by jhgould** [comment]
Committing so Derek and I can start working on tests.

**Review by jhgould — APPROVED** [review]

**Review by muydanny — APPROVED** [review]

**Pull request merged**
